{% set version = "0.1.40" %}

package:
  name: jax
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: 59c91ad639b7587a923c2baacafb98d4a6dfd2ea3cd6312b18bfa6ee1a3b0b2b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - absl-py
    - numpy >=1.12
    - opt_einsum
    - protobuf >=3.6.0
    - six
    - jaxlib

test:
  imports:
    # these tests imports jaxlib which is a Google non-compliant manylinux1 wheel.
    # - jax
    # - jax.experimental
    # - jax.interpreters
    # - jax.lax
    # - jax.lib
    # - jax.numpy
    # - jax.ops
    # - jax.scipy
    # - jax.scipy.stats
    # - jax.tools
    - numpy  # dummy

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Differentiate, compile, and transform Numpy code"

extra:
  recipe-maintainers:
    - ocefpaf
