{% set name = "jax" %}
{% set version = "0.4.35" %}

package:
  name: {{name}}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/{{name}}/{{name}}-{{ version }}.tar.gz
  sha256: c0c986993026b10bf6f607fecb7417377460254640766ce40f1fef3fd139c12e

build:
  number: 1
  # Matches jaxlib-feedstock's compatibility
  skip: true  # [s390x or py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - numpy >=1.24    # [py<312]
    - numpy >=1.26.0  # [py>=312]
    - opt_einsum
    - scipy >=1.10  # [py<312]
    - scipy >=1.11.1  # [py>=312]
    - jaxlib {{version}}
    # Not declared in the metadata but essential to this package.
    - importlib_metadata >=4.6  # [py<310]
    - ml_dtypes >=0.4.0
  run_constrained:
    - protobuf >=3.13,<4

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code
  description: |
    JAX is Autograd and XLA, brought together for high-performance numerical computing and machine learning research. It provides composable transformations of Python+NumPy programs: differentiate, vectorize, parallelize, Just-In-Time compile to GPU/TPU, and more.
  dev_url: https://github.com/google/jax
  doc_url: https://jax.readthedocs.io/

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
