{% set name = "jax" %}
{% set version = "0.7.2" %}

package:
  name: {{name}}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/{{name}}/{{name}}-{{ version }}.tar.gz
  sha256: 71a42b964bc6d52e819311429e6c0f5742e2a4650226dab1a1dd26fd986ca70d

build:
  number: 0
  # Matches jaxlib-feedstock's compatibility
  skip: true  # [s390x or py<311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - numpy >=2.0
    - numpy >=1.26.0  # [py>=312]
    - opt_einsum
    - scipy >=1.13
    - scipy >=1.11.1  # [py>=312]
    - jaxlib >=0.7.2,<=0.7.2
    # Not declared in the metadata but essential to this package.
    - importlib_metadata >=4.6  # [py<310]
    - ml_dtypes >=0.5.0
  run_constrained:
    - jaxlib ==0.7.2
    - jax-cuda12-plugin >=0.7.2,<=0.7.2
    - jax-cuda13-plugin >=0.7.2,<=0.7.2
    - jax-rocm60-plugin >=0.7.2,<=0.7.2
    - libtpu ==0.0.23

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code
  description: |
    JAX is Autograd and XLA, brought together for high-performance numerical computing and machine learning research. It provides composable transformations of Python+NumPy programs: differentiate, vectorize, parallelize, Just-In-Time compile to GPU/TPU, and more.
  dev_url: https://github.com/google/jax
  doc_url: https://jax.readthedocs.io/

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
