{% set name = "jax" %}
{% set version = "0.4.16" %}

package:
  name: {{name}}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/{{name}}/{{name}}-{{ version }}.tar.gz
  sha256: e2ca82c9bf973c2c1c01f5340a583692b31f277aa3abd0544229c1fe5fa44b02

build:
  number: 0
  # Matches jaxlib-feedstock's compatibility
  skip: true  # [ppc64le or s390x or win or py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - numpy >=1.21,<2  # [py>=310 or (osx and arm64)]
    - numpy >=1.20,<2  # [py<310 and not (osx and arm64)]
    - opt_einsum
    - scipy >=1.5
    - typing_extensions
    # Not declared in the metadata but essential to this package.
    # Update minimum from https://github.com/google/jax/blob/jaxlib-v0.3.25/jax/version.py
    - jaxlib >=0.3.22

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code
  description: |
    JAX is Autograd and XLA, brought together for high-performance numerical computing and machine learning research. It provides composable transformations of Python+NumPy programs: differentiate, vectorize, parallelize, Just-In-Time compile to GPU/TPU, and more.
  dev_url: https://github.com/google/jax
  doc_url: https://jax.readthedocs.io/

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
  skip-lints:
    - missing_license_url
    - missing_doc_source_url
