{% set name = "jax" %}
{% set version = "0.4.25" %}

package:
  name: {{name}}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/{{name}}/{{name}}-{{ version }}.tar.gz
  sha256: a8ee189c782de2b7b2ffb64a8916da380b882a617e2769aa429b71d79747b982

build:
  number: 1
  # Matches jaxlib-feedstock's compatibility
  skip: true  # [s390x or py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - numpy >=1.22    # [py<311]
    - numpy >=1.23.2  # [py==311]
    - numpy >=1.26.0  # [py>=312]
    - opt_einsum
    - scipy >=1.9  # [py<312]
    - scipy >=1.11.1  # [py>=312]
    # Not declared in the metadata but essential to this package.
    # Update minimum from https://github.com/google/jax/blob/jaxlib-v0.3.25/jax/version.py
    - jaxlib >=0.4.19
    - importlib_metadata >=4.6  # [py<310]
    - ml_dtypes >=0.2.0
  run_constrained:
    - protobuf >=3.13,<4

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code
  description: |
    JAX is Autograd and XLA, brought together for high-performance numerical computing and machine learning research. It provides composable transformations of Python+NumPy programs: differentiate, vectorize, parallelize, Just-In-Time compile to GPU/TPU, and more.
  dev_url: https://github.com/google/jax
  doc_url: https://github.com/jax-ml/jax/blob/main/README.md

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
