{% set version = "0.2.0" %}

package:
  name: jax
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: 70ddde302e92b92a122a1e9ae796353d70b0b52f20ae5d0d154c3c1ffd8b623b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - absl-py
    - numpy >=1.12
    - opt_einsum
    - protobuf >=3.6.0
    - six
    - jaxlib
    - fastcache

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
