{% set version = "0.2.11" %}

package:
  name: jax
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: 702ea67ce2c06f8dd868559c51c7cdf93e7f77aec239537922d716ab91dffc63

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - absl-py
    - numpy >=1.12
    - opt_einsum
    # Not declared in the metadata but essential to this package.
    - jaxlib

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
