travis:
  secure:
    BINSTAR_TOKEN: KD1p8CNr27K3Vk+4yJYskL2V0mUMHbDf8H1a1g4b0L572O2ZmH+Ue+Li5g01T9VhJFKioXqf6rDO+kzxCMXwu+pNA1Q710vNC20Yik0X/JmmXxQqMJf9Tl9AGe3zVtvhWIU2qHMX9lhs4pBuGEHRvsHEcWHgw00S7QFos1L/eGagbKqCuNhBTEuThh0uCV4ZCkNl5HJhz9QT2yw3Yhl90u+cVzwHZK8ZObL3vpjegU9igau9V49QGuAgYpxAiTsE0hlFmRG3Mtv1iy37XjXbtSAjOEk92S54+J0Hpac4b1kAuooloBOKGtaoqOO3hFL8C9JJ6P2SwJNJ5dN7W0BzzqiH7wzsw59wSGz0ELp027kY7DuHOui+FlhhgiSm5ADvaPEkBKY8cCmvagjDJ/y+BR5tVpSlAEaOSv5n+GyO600HKd4bn4GBVuOr+OHa0egk7tZlrBgMge5QuqtOUAgo4N3xGp4uf2yMxjrAcgdI2OvnzzD6FpJXNDShcEdma8AvS55RkyXOroT64jDbbpNilssT3HqZjUMVrXVEJT1DZiQo94HDE74Pqu988P/Nm3mKvxp/1v6vAwzdpz4+gv+hwVykY+C0DMENXnACN6JuFWbrZnLgAuNeSgXdOEZt15wxe3ogz8Yconmm+XJWT5nA3Tf/MkOFVEx8ETqGVrDooe4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
